"""Publishing Agent - Formats and exports insights.

The PublishingAgent persists agent outputs to the filesystem in human-readable
formats. It supports:
  - markdown (.md): Default; includes YAML-style metadata headers
  - txt (.txt): Plain text for simple sharing
  - export_reflection: Formats ReflectionAgent output as a structured report
  - list_published: Shows recently exported files

Published files are written to ~/Desktop/SecondBrainPublished/ by default,
making them immediately accessible to the user. All publish events are logged
to telemetry for tracking.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from brainos.core import load_config
from brainos.telemetry.schema import TelemetryDB


class PublishingAgent:
    """Agent that formats and exports content."""

    def __init__(self):
        """Initialize publishing agent."""
        self.config = load_config()
        self.telemetry = TelemetryDB(
            self.config.paths.get("telemetry_db", "./.brainos/telemetry.db")
        )
        self.publish_dir = Path.home() / "Desktop" / "SecondBrainPublished"
        self.publish_dir.mkdir(parents=True, exist_ok=True)

    def publish(self, content: str, title: str, format_type: str = "markdown") -> Dict[str, Any]:
        """Publish content.

        Args:
            content: Content to publish
            title: Title/filename
            format_type: "markdown", "html", "txt", "pdf"

        Returns:
            Dict with publication details
        """
        timestamp = datetime.utcnow().isoformat()
        safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in title)
        safe_title = safe_title.replace(" ", "_")[:50]

        try:
            if format_type == "markdown":
                filename = f"{safe_title}_{timestamp.split('T')[0]}.md"
                filepath = self.publish_dir / filename

                # Add metadata
                output = f"""# {title}

**Published**: {timestamp}

---

{content}

---

*Generated by Second Brain OS*
"""
                with open(filepath, "w") as f:
                    f.write(output)

            elif format_type == "txt":
                filename = f"{safe_title}_{timestamp.split('T')[0]}.txt"
                filepath = self.publish_dir / filename

                output = f"""{title}
Published: {timestamp}

{content}

---
Generated by Second Brain OS
"""
                with open(filepath, "w") as f:
                    f.write(output)

            else:
                return {
                    "status": "error",
                    "error": f"Format {format_type} not yet supported",
                }

            # Log to telemetry
            self.telemetry.log_event(
                "publish",
                query=title,
                metadata={"format": format_type, "filepath": str(filepath)},
            )

            return {
                "status": "success",
                "title": title,
                "format": format_type,
                "filepath": str(filepath),
                "url": f"file://{filepath}",
                "message": f"Published to {filepath}",
            }

        except Exception as e:
            return {
                "status": "error",
                "title": title,
                "error": str(e),
            }

    def export_reflection(self, reflection_data: Dict[str, Any]) -> Dict[str, Any]:
        """Export a reflection report.

        Args:
            reflection_data: Reflection output from reflection agent

        Returns:
            Dict with export details
        """
        timestamp = datetime.utcnow().isoformat().split("T")[0]
        filename = f"reflection_{timestamp}.md"
        filepath = self.publish_dir / filename

        try:
            # Format reflection as markdown
            output = f"""# Knowledge Reflection Report

**Generated**: {timestamp}

## Summary

- Total Concepts: {reflection_data.get('summary', {}).get('total_concepts', 'N/A')}
- Total Connections: {reflection_data.get('summary', {}).get('total_connections', 'N/A')}
- Graph Density: {reflection_data.get('summary', {}).get('graph_density', 'N/A')}

## Core Concepts

"""

            for concept, connections in reflection_data.get("core_concepts", []):
                output += f"- **{concept}** ({connections} connections)\n"

            if reflection_data.get("blindspots"):
                output += "\n## Knowledge Blindspots\n\n"
                for blindspot in reflection_data["blindspots"][:5]:
                    output += f"- {blindspot}\n"

            if reflection_data.get("suggested_connections"):
                output += "\n## Suggested Connections\n\n"
                for sugg in reflection_data["suggested_connections"][:5]:
                    output += f"- **{sugg['source']}** ↔ **{sugg['target']}**: {sugg['reason']}\n"

            with open(filepath, "w") as f:
                f.write(output)

            self.telemetry.log_event(
                "publish_reflection",
                metadata={"filepath": str(filepath)},
            )

            return {
                "status": "success",
                "filepath": str(filepath),
                "message": f"Reflection exported to {filepath}",
            }

        except Exception as e:
            return {
                "status": "error",
                "error": str(e),
            }

    def list_published(self) -> Dict[str, Any]:
        """List published files.

        Returns:
            Dict with list of published files
        """
        files = list(self.publish_dir.glob("*"))
        files.sort(key=lambda x: x.stat().st_mtime, reverse=True)

        return {
            "status": "success",
            "directory": str(self.publish_dir),
            "published_count": len(files),
            "files": [
                {
                    "name": f.name,
                    "path": str(f),
                    "size": f.stat().st_size,
                    "modified": datetime.fromtimestamp(f.stat().st_mtime).isoformat(),
                }
                for f in files[:10]
            ],
        }
